# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hapt_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import hapt
import numpy as np

DATASET = None
ITERATIONS = 0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 560)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 180, 611, 301))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(49)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 498, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(206, 75, 0);\n"
"color: rgb(50, 101, 101);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(45, 79, 152)")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Lao")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("color: rgb(255, 170, 0)")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 60, 174, 60))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(206, 75, 0);\n"
"color: rgb(50, 101, 101);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(980, 350, 121, 60))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 187, 160);\n"
"color: rgb(50, 101, 101);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(880, 240, 231, 119))
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(45, 79, 152)")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(940, 420, 161, 60))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 187, 160);\n"
"color: rgb(50, 101, 101);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(810, 320, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.start)
        self.pushButton_2.clicked.connect(self.stabilize)
        self.pushButton_4.clicked.connect(lambda: self.sk_builtins('kmeans'))
        self.pushButton_5.clicked.connect(lambda: self.sk_builtins('hierarchical'))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start(self):
        global ITERATIONS
        global DATASET
        iterations = int(self.spinBox.text()) - ITERATIONS
        if iterations < 0:
            iterations = int(self.spinBox.text())
            DATASET = None
        ITERATIONS = int(self.spinBox.text())
        results, dataset = hapt.kmeans(DATASET, iterations)
        DATASET = dataset
        print(results)
        # enumerate the cluster distribution for each activity type
        for activity_no, clustering in enumerate(results):
            for cluster, total in enumerate(clustering):
                print(activity_no, cluster, total)
                item = QtWidgets.QTableWidgetItem(str(total))
                if total == np.max(results[:, cluster]):
                    font = QtGui.QFont('Times', 12)
                    font.setBold(True)
                    item.setFont(font)
                    self.tableWidget.setItem(
                        6, cluster, QtWidgets.QTableWidgetItem(str(total / np.sum(results[:, cluster]) * 100) + '%'))

                self.tableWidget.setItem(activity_no, cluster, item)

    def stabilize(self):
        global ITERATIONS
        global DATASET
        results, dataset, iterations = hapt.kmeans_stabilize(DATASET)
        ITERATIONS += iterations
        self.spinBox.setValue(iterations)
        DATASET = dataset
        # enumerate the cluster distribution for each activity type
        for activity_no, clustering in enumerate(results):
            for cluster, total in enumerate(clustering):
                item = QtWidgets.QTableWidgetItem(str(total))
                if total == np.max(results[:, cluster]):
                    font = QtGui.QFont('Times', 12)
                    font.setBold(True)
                    item.setFont(font)
                    self.tableWidget.setItem(
                        6, cluster, QtWidgets.QTableWidgetItem(str(total / np.sum(results[:, cluster]) * 100) + '%'))
                self.tableWidget.setItem(activity_no, cluster, item)

    def sk_builtins(self, algorithm):
        if algorithm == "kmeans":
            results = hapt.scikit_kmeans()
        if algorithm == "hierarchical":
            results = hapt.scikit_hierarchical()
        # enumerate the cluster distribution for each activity type
        for activity_no, clustering in enumerate(results):
            for cluster, total in enumerate(clustering):
                item = QtWidgets.QTableWidgetItem(str(total))
                if total == np.max(results[:, cluster]):
                    font = QtGui.QFont('Times', 12)
                    font.setBold(True)
                    item.setFont(font)
                    self.tableWidget.setItem(
                        6, cluster, QtWidgets.QTableWidgetItem(str(total / np.sum(results[:, cluster]) * 100) + '%'))
                self.tableWidget.setItem(activity_no, cluster, item)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "K-means Clustering"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "WALKING"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "WALKING_UPSTAIRS"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "WALKING_DOWNSTAIRS"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "SITTING"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "STANDING"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "LAYING"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Precizie"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Iterații"))
        self.pushButton_2.setText(_translate("MainWindow", "Stabilizează"))
        self.pushButton_4.setText(_translate("MainWindow", "K-Means"))
        self.label_3.setText(_translate("MainWindow", "Scikit built-ins"))
        self.pushButton_5.setText(_translate("MainWindow", "Hierarchical"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
